project:
  type: book

book:
  title: "Environmental Data Visualization"
  subtitle: 'A course on the theory and practice of communication through data visualization'
  author: "Michael McCarthy, PhD"
  #affiliation: "Pitzer College"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - part: weather.qmd
      chapters:
      - information.qmd
      - coding1.qmd
      - maps1.qmd
      - maps2.qmd
      - chartJunk.qmd
      - assignment1.qmd
    - part: EJ.qmd
      chapters:
      - EJtheory.qmd
      - context.qmd
      - EJtools.qmd
      - aviation.qmd
      - EJdata.qmd
      - debt.qmd
      - assignment2.qmd
    - part: data.qmd
      chapters:
      - import2.qmd
      - export.qmd
      - munging.qmd
      - import3.qmd
      - assignment3.qmd  
  appendices: 
    - syllabus.qmd  
    - tools.qmd
    - resources.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: united
    toc: true
    toc-depth: 4
    code-link: true
    



