# Assignments for Unit 1 {#sec-assignment1}

::: {.callout-note appearance="simple"}
This includes the list of assignments for Unit 1
:::

```{r}
#| label: tbl-unit1assignments
#| tbl-cap: Assignments from Unit 1
#| echo: false
#| warning: false
library(dplyr)
library(kableExtra)


assignment <- c('Install R', 'Install RStudio', 'Visual Salience Reading',
          'R Graphics Cookbook - Preface and 1.1 through 1.5 in R Basics',
          'R for Data Science - 3. Data Visualization', 'Leaflet for R',
          'LA Times - Prof. Phillips - Warehouse Growth', 'Guardian - Maanvi Singh - Ontario Warehouses')
due.Date <- c('Jan 20, 2023', 'Jan 20, 2023', 'Jan 25, 2023', 'Jan 25, 2023', 'Jan 27, 2023', 'Jan 27, 2023',
              'Feb 1, 2023', 'Feb 1, 2023')
source <- c('https://mikem-radicalresearch.quarto.pub/environmental-data-visualization/tools.html',  'https://mikem-radicalresearch.quarto.pub/environmental-data-visualization/tools.html',          'http://www.scholarpedia.org/article/Visual_salience', 'https://r-graphics.org/',
            'https://r4ds.had.co.nz/data-visualisation.html', 'https://rstudio.github.io/leaflet/',
            '', 'https://www.theguardian.com/us-news/2022/sep/13/ontario-california-amazon-warehouses')

unit1 <- data.frame(assignment, due.Date, source)# %>% 

unit1 %>% mutate(link = cell_spec(row.names(.), 'html', link = source)) %>% 
  select(-source) %>% 
  kableExtra::kable('html', escape = FALSE) %>% 
  kable_material_dark(c('condensed', 'hover')) %>% 
  column_spec(1, width = '20em') #%>% 
  #column_spec(3, link = 'html')

```

## Graded Assignment - Visualization Critique Paper

Choose a environmental data visualization. This can include static figures, interactive graphics, infographics, apps, videos, animations, etc. Please get approval from Mike if you are choosing something that may not meet a standard definition of an environmental data visualization.  

Write a two-page paper (12-point font or less) describing the visualization and salient features that you think are interesting and noteworthy. Include a **picture or link** to your chosen visualization (does not count towards 2-page minimum). In your critique, please include ten individual points that fit into at least one of these categories. Include at least 3 of these categories in your paper.

1. Things that you like, or think are done well
2. Things that you dislike, or think are done poorly
3. Improvements you would make to the visualization (can be additions or subtractions from features in the visualization)
4. Features that provide interesting structure to the data and make it more informative
5. Features that you find aid in communicating knowledge or help **tell the story**.  

Assignment is due February 2, 2023 at the beginning of class.  Assignments can be emailed or physically turned in. This assignment is worth 150 points. Spelling, grammar, and sentence structure will be a minor component of the score (~10 points).    