# California Environmental Voters {#sec-enviroVoters}

::: {.callout-note appearance="simple"}
Today we have a guest lecture from California Environmental Voters Youth Organizing Ambassadors Yolanda Aguilar Candelario, Leah Harrison-Lurie, and Lisa Imai.    
:::
  
## California Environmental Voters [WE CAN](https://envirovotersedfund.org/we-can-volunteer/)

**Yolanda Aguilar Candelario** - In her work, [Yolanda](https://envirovotersedfund.org/who-we-are/staff/) leads the Ambassador Program where she supports the empowerment of young leaders to champion in organizing and political power among key climate crisis issues. Yolanda graduated from the [University of California, Riverside](https://www.ucr.edu/) with a Master in Public Policy with a research focus on youth civic engagement throughout the Inland Empire. She previously worked with The Outreach Team where she worked on quality control metrics to ensure equity across voter registration and voter contact on the ground in the state of Pennsylvania. In addition, Yolanda served as an intern with County of Riverside and a Fellow with the [Western Riverside Council of Governments](https://www.wrcog.us/) where she worked closely with their Government Affairs team to support internship/fellowship programs equipped for our future leaders. Yolanda’s goal is to mobilize young people, especially BIPOC. In her free time, Yolanda enjoys trying new coffee shops, spending time with her adorable nephews and nieces, and learning ways to get involved in her community. 

**Leah Harrison-Lurie** - Leah is a junior at Pitzer College, pursuing a self-designed major in Health, Justice, and Human Rights, with a focus on the particular applications of public health and political knowledge to the abolition of the prison industrial complex. On campus, she is involved in the Claremont Colleges Prison Abolition Collective's Political Education team, and is currently planning and facilitating a speaker and workshop series that will bring several prominent abolitionist scholar/activists to Claremont throughout the course of the spring of 2023. She is passionate about the intersection of environmental justice and prison industrial complex abolition organizing. Leah is also involved in the Claremont Students for Public Health student organization, and is currently working to establish a public health program at the Claremont Colleges. Outside of school, Leah loves to read, surf, hike, spend quality time with friends and family, and cook. 

**Lisa Imai** - Lisa graduated from UCLA in 2021 with a degree in Environmental Science. In 2022, she completed a 10-month SEI Climate Corps Fellowship at Facilities Planning and Program Services, Inc. (FPPS). She continues to work for FPPS full time from her home in Corona as a Project and Energy/Sustainability Coordinator, tracking and reporting sustainability performance for California Community Colleges in ENERGY STAR Portfolio Manager and AASHE STARS. Lisa is a LEED Green Associate and WELL Accredited Professional, with additional training in climate advocacy and DEI. Lisa has a miniature Schnoodle named Ducky, likes themed entertainment and musical theatre, and enjoys reminiscing about when she used to engage in her hobbies of reading, painting, and sewing.

